FROM centos:7

MAINTAINER TEAM2-CLOUDDNS

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum update
RUN yum -y install iproute
RUN yum -y install iputils
RUN yum -y install openssh-server
RUN yum -y install traceroute
RUN yum -y install iptables
RUN yum -y install tcpdump
RUN yum -y install python
RUN yum -y install epel-release
RUN yum -y install python-pip
RUN pip install paramiko
RUN yum -y install bind bind-utils
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
